project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "Data Exercise"
            href: ./dataanalysis_exercise.html
      - text: "Flu Analysis"
        menu:
          - text: "Wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "Fitting"
            href: ./fluanalysis/code/fitting
          - text: "Explorations"
            href: ./fluanalysis/code/explorations.html
    right:
      - icon: github 
        href: https://kellyhatfield.github.io/kellyhatfield-MADA-portfolio/     

format:
  html:
    theme: Lumen
    highlight: zenburn
    css: styles.css
    toc: FALSE


